# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170704_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='alias',
            new_name='en_title',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔', max_length=100, null=True, verbose_name='标签'),
        ),
    ]
