# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170705_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='en_title',
        ),
    ]
