# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parentcomment',
            new_name='parent',
        ),
    ]
