# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=200, upload_to='user_images/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
